#! /bin/bash

SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
HOST_ROOT="$( cd $(dirname "$0")/..>/dev/null 2>&1 ; pwd -P )"
FORCE=$([ "$A" == "-f" ] && echo Y)
echo $HOST_ROOT

# Build the extra image.  This is skipped if the image exists unless "-f" is specified

build_extra() {
  local repo="$1" ver="$2" repo_ver="$2-$3"
  local tag="${ver}-extra" ; tag=${tag%-}
  local target="${repo}:${tag}"
  local -u VNAME="${repo}_VER"
  local id=$(docker images $target --format '{{.ID}}')

  # skip if image already build unless -f option set
  [ -n "$id" ] && [ -z "$FORCE"  ] && return 0
  [ -n "$id" ] && docker rmi $target
  
  echo "Entering build $target"
  docker build \
    -f $SCRIPT_PATH/${repo}-dockerfile \
    -t $target                         \
    --build-arg $VNAME=$repo_ver       \
    --build-arg HOST_ROOT="$HOST_ROOT" \
    $SCRIPT_PATH >> /tmp/${repo}-${ver}.log
  echo "Build of $target completed"

  tail -2 /tmp/${repo}-${ver}.log
}

# Do any builds in parallel. Note that php:7.2 doesn't have a bullseye version

build_extra debian  bullseye              &
build_extra httpd   2.4      bullseye     &
build_extra php     7.2      fpm-buster   &
build_extra php     8.0      fpm-bullseye
