version: "3.3"

services:

  apache2:
    image: alpine:${ALPINE_VERSION}
    hostname: apache2
    container_name: ${VHOST}_apache2
    depends_on:
      - php
      - mysql
    restart: on-failure
    volumes:
      - ./apache2/conf:/usr/local/apache2/conf:ro
      - ${WWW_IPB_ROOT}:/var/www/ipb
      - var_log:/var/log
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    secrets:
      - fullchain
      - privkey
    environment:
      VHOST: ${VHOST}
      HOST_IP: ${SUBNET}.2
      HTTPS_PORT: ${HTTPS_PORT}
      APACHE_LOG_DIR: /var/log/apache2
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.2

  php:
    image: alpine:${ALPINE_VERSION}
    hostname: php
    container_name: ${VHOST}_php
    depends_on:
      - mysql
      - redis
    restart: on-failure
    volumes:
      - ./php:/usr/local/php:ro
      - ${WWW_IPB_ROOT}:/var/www/ipb
      - var_log:/var/log
    environment:
      VHOST: ${VHOST}
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.3

  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    container_name: ${VHOST}_mysql
    restart: on-failure
    volumes:
      - ./mysql/etc/mysql.cnf/:/etc/mysql/conf.d/mysql.cnf:ro
      - mysql_data:/var/lib/mysql
      - var_log:/var/log
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
      VHOST: ${VHOST}
    secrets:
      - mysql-root
    security_opt:
      - seccomp:unconfined
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.4

  redis:
    image: alpine:${ALPINE_VERSION}
    hostname: redis
    container_name: ${VHOST}_redis
    restart: on-failure
    secrets:
      - redis-pwd
    volumes:
      - ./redis:/usr/local/redis:ro
      - redis_data:/var/lib/redis
      - var_log:/var/log
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.5

  hk:
    image: alpine:${ALPINE_VERSION}
    hostname: hk
    container_name: ${VHOST}_hk
    domainname: buildhub.local
    volumes:
      - ./etc/hk:/usr/local/hk/conf:ro
      - ./bin/hk:/usr/local/hk/conf:ro
      - var_log:/var/log
      - /run/docker-app-callback.pipe:/run/host-callback.pipe
      - backups:/backups
    environment:
      VHOST: ${VHOST}
    depends_on:
      - apache2
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.6

networks:
  AMPstack:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/24

secrets:
  fullchain:
    file: .secrets/fullchain.pem
  privkey:
    file: .secrets/privkey.pem
  mysql-root:
    file: .secrets/mysql-root
  redis-pwd:
    file: .secrets/redis-pwd

volumes:
  mysql_data:
    external:
      name: ${VHOST}_mysql_data
  var_log:
    external:
      name: ${VHOST}_var_log
  backups:
    external:
      name: ${VHOST}_backups
  redis_data:
    external:
      name: ${VHOST}_redis_data
