version: "3.7"

services:

  httpd:
    image: httpd
    hostname: httpd
    container_name: ${VHOST}_httpd
    domainname: buildhub.local
    build:
      context: .
      dockerfile: httpd-dockerfile
    depends_on:
      - php
      - mysql
    restart: always
    volumes:
      - ${WWW_IPB_ROOT}:/var/www/ipb
      - var_log:/var/log
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    secrets:
      - fullchain
      - privkey
    environment:
      - VHOST=${VHOST}
      - HOST_IP=${SUBNET}.2
      - HTTPS_PORT=${HTTPS_PORT}
      - APACHE_LOG_DIR=/var/log/apache2
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.2

  php:
    image: php
    hostname: php-fpm
    container_name: ${VHOST}_php
    domainname: buildhub.local
    build:
      context: .
      dockerfile: php-dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
      - redis
    restart: always
    volumes:
      - ${WWW_IPB_ROOT}:/var/www/ipb
    environment:
      - VHOST=${VHOST}
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.3

  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: mysql
    container_name: ${VHOST}_mysql
    domainname: buildhub.local
    restart: always
    volumes:
      - ./etc/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TZ}
      - VHOST=${VHOST}
    secrets:
      - mysql-root
    security_opt:
      - seccomp:unconfined
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.4

  redis:
    image: "redis:6.2-bullseye"
    hostname: redis
    container_name: ${VHOST}_redis
    domainname: buildhub.local
    command: redis-server --requirepass ${REDIS_PWD}
    restart: always
    secrets:
      - redis-pwd
    volumes:
      - redis_data:/var/lib/redis
      - ./etc/redis:/usr/local/etc/redis:ro
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.5

  hk:
    image: hk
    hostname: hk
    container_name: ${VHOST}_hk
    domainname: buildhub.local
    build:
      context: .
      dockerfile: hk-dockerfile
    restart: always
    init: true
    volumes:
      - var_log:/var/log
      - /run/docker-app-callback.pipe:/run/host-callback.pipe
      - backups:/backups
    environment:
      - VHOST=${VHOST}
    depends_on:
      - httpd
    networks:
      AMPstack:
        ipv4_address: ${SUBNET}.6

networks:
  AMPstack:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}.0/24

secrets:
  fullchain:
    file: .secrets/fullchain.pem
  privkey:
    file: .secrets/privkey.pem
  mysql-root:
    file: .secrets/mysql-root
  redis-pwd:
    file: .secrets/redis-pwd

volumes:
  mysql_data:
    external:
      name: ${DBHOST}_mysql_data
  var_log:
    external:
      name: ${VHOST}_var_log
  backups:
    external:
      name: ${VHOST}_backups
  redis_data:
    external:
      name: ${VHOST}_redis_data
